openapi: 3.1.0
info:
  title: PetStore API
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /pets:
    get:
      summary: List all pets
      parameters:
        - in: query
          name: category
          schema:
            type: string
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    category:
                      type: string
                  required:
                    - id
                    - name
                    - category